### PR TITLE
implemented std::error::Error for ParseError

### PR DESCRIPTION
**Pull request by khoda81**
issue: #5

### CODE REVIEW

**Comment by Robbepop** [comment]
I see you are probably using this crate for your sudoku solver. Would it also be possible to use the superior and newer [`cnf-parser` crate](https://crates.io/crates/cnf-parser) instead or do you need full DIMACS support and not just CNF support?

**Comment by khoda81** [comment]
`cnf-parser` is actually perfectly fine for me. I found `dimacs-parser` through a google search but not this one.
And yes I am expanding the sudoku algorithm to solve any cnf instance.

**Comment by Robbepop** [comment]
> `cnf-parser` is actually perfectly fine for me. I found `dimacs-parser` through a google search but not this one. And yes I am expanding the sudoku algorithm to solve any cnf instance.

Okay cool. I'd definitely recommend you to use the `cnf-parser` crate then. This crate is heavily outdated and unmaintained which is also why I usually do not accept PRs. I will accept your though since it is a simple improvement.

**Review by Robbepop — APPROVED** [review]
LGTM

**Pull request merged**
